# Generated by Django 4.1.3 on 2022-11-23 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='good',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='good',
            name='old_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='size',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='good',
            name='use_for',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
