# Generated by Django 4.1.3 on 2022-11-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_rename_title_good_name_good_old_price_good_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='image',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
